apiVersion: argoproj.io/alpha1
kind: Application
metadata: 
  name: argocd-sample-application
  namespace: argocd-applications
spec:
  project: default
  source:
    repoURL: https://github.com/aafaq-rashid-comprinno/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-testing

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
